apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-demo-yii2
  labels:
    app: ci-demo-yii2
    environment: test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 3
  selector:
    matchLabels:
      app: ci-demo-yii2
      environment: test
  template:
    metadata:
      labels:
        app: ci-demo-yii2
        environment: test
    spec:
      containers:
      - name: ci-demo-yii2
        image: 192.168.77.133:5000/root/ci-demo-yii2:dev
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        readinessProbe:
            httpGet:
              path: /
              port: http
        env:
        - name: _PLEASE_REDEPLOY
          value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'

---
apiVersion: v1
kind: Service
metadata:
  name: ci-demo-yii2
  namespace: default
  labels:
    app: ci-demo-yii2
    environment: test
spec:
  selector:
    app: ci-demo-yii2
    environment: test
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30082